# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Knowmore
description: > # this means to ignore newlines until "baseurl:"
  Knowmore is a wiki style website designed to offer short and simple guides on a wide variety of topics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://knowmore.viri.space" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

defaults:
  -
    scope:
      path: "topics"
      type: "pages"
    values:
      layout: "default"

nav_pages:
  - index.md
  - about.md
  - contribute.md
  - topics/topics.md

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
